# Generated by Django 2.0.2 on 2018-10-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
