# Generated by Django 2.0.2 on 2018-10-03 08:59

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181003_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to=main.models.directory_path),
        ),
    ]
