# Generated by Django 2.0.2 on 2018-10-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20181003_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name_plural': 'users'},
        ),
    ]
